// AUTO-GENERATED by tools/angular-docs/merge-compodoc-json.mjs
export const compodocJson = {
  "pipes": [],
  "interfaces": [],
  "injectables": [],
  "guards": [],
  "interceptors": [],
  "classes": [],
  "directives": [],
  "components": [],
  "modules": [],
  "miscellaneous": [],
  "routes": {
    "name": "<root>",
    "kind": "module",
    "children": []
  }
} as const;
