name: Main PR CI
env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_VERBOSE_LOGGING: true

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      - run: corepack enable

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      - run: yarn dlx nx start-ci-run --distribute-on=".nx/workflows/distribution-config.yaml" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'yarn'

      - uses: nrwl/nx-set-shas@v4

      - run: yarn install --immutable
      # When you enable task distribution, run the e2e-ci task instead of e2e
      - run: yarn nx affected -t test build e2e-ci
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: yarn nx fix-ci
        if: always()
